name: Java CI with Maven

permissions:
  id-token: write
  contents: read
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Djacoco.skip=true -DdisableXmlReport=true
        
      - name: List files in target directory after build
        run: ls -la target

      - name: Archive Production Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: production-build
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Production Artifact
        uses: actions/download-artifact@v2
        with:
          name: production-build
          path: ./target

      - name: List files in target directory after download
        run: ls -la ./target

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: './target/spring-petclinic-rest-3.2.1.jar'
